### ISSUE TITLE
interface problem

### ISSUE THREAD

**Issue by akh33l** [Erickesau/Orion-Face-Recognition-system#1]
thanks for you work

when I start the code its run but when i try fo add new face or make search the interface still rigid and i cant add face or make search because it still in background

**Comment by Erickesau** [comment]
> thanks for you work
> 
> when I start the code its run but when i try fo add new face or make search the interface still rigid and i cant add face or make search because it still in background


thanks for reporting the bug, 
--usually when the program is processing a new face it disables the controls until it gets the result, 
--try a lighter image 100kb and wait longer because it uses a lot of cpu, 
--could you please specify your platform and Python version, 
--were you able to pickup the image with the file dialog?
--does the search from the camera work?

**Comment by akh33l** [comment]
i cant add any faces because adding windows stay in background
im using linux

**Comment by Erickesau** [comment]
so you can switch between the tabs in the program but when you click the add image button the file dialog doesn't show up, i was googling and it seems to be a common bug in tkinter, i created two files copy & paste into the Projet root folder & run the first one tries to show the file dialog on top of the interface if this doesn't work for you then try the second one it will hide the program interface so you can see the file dialog.  please let me know which one worked for you.

[https://www.mediafire.com/file/njcz1l2ngxg3b09/test_1_Orion_FRS_v1.2.8.py/file]()

[https://www.mediafire.com/file/y4jyavs5h1ny6q5/test_2_Orion_FRS_v1.2.8_-_Copy.py/file]()


Code Example:
from tkinter import filedialog, Tk
root = Tk()
root.withdraw() #hide program interfase
filename = filedialog.askopenfilename(master=root) #set master=root
root.deiconify() #show program interfase
root.mainloop()

**Comment by akh33l** [comment]
ok 
thanks a lot
the second file test 2 Orion FRS v1.2.8 - Copy.py works and upload photos but after that wont write the information and cant add new person and start write information in terminal
for searching it takes the photo and make searching

i hope if you make it work with HOG algorithm 
and if you can make it search for all database of images
if it find a result show it and make a new option of continue

**Comment by akh33l** [comment]
test 1 Orion FRS v1.2.8.py

the same problem as before

**Comment by Erickesau** [comment]
Ok the second test work thankyou.

i like the idea of ​​HOG algorithm i think i can do it with opencv to extract only the face instead of using the whole photo i have the idea to do it in future versions.  

and about the search you mean to add the option to search in multiple image files for example an entire folder and if a result is found show it and add a button to continue scanning

**Comment by Erickesau** [comment]
the encoding of some images gives an error when the face recognition module reads them the program shows a message saying that an error occurred and I have to convert the image using any converter to be able to add a new face I do not know if that is the error the one you get. 

-- try to add a new face but use one of the images from the database folder those images have already been tested and are accepted by the program and let me know if any errors occur.

-- which version of Python do you use? 

-- Could you please send me some screenshots when the program writes the information in the terminal, I don't know why it happens hopefully we can fixit.

**Comment by Erickesau** [comment]
hello and found the error that prevents you from adding new faces I tried the file and it was while solving the previous error that I made a mistake on line 1346 but I already deleted it, the program had topmost enabled, that's why the message was not displayed and it remained in the background .

https://www.mediafire.com/file/t8b4p6eezihz12k/test_3_Orion_FRS_v1.2.8_fixed_for_linux.py/file

**Comment by akh33l** [comment]
thank you brother
here is the problem
the program wont get the information and complete operation
i made a small video about the problem

https://www.mediafire.com/file/afruil089e2ioov/simplescreenrecorder-2022-08-27_17.43.38.mp4/file

**Comment by akh33l** [comment]
can you modify the repo by adding camera recognition and make search for all faces in data set
i mean to put new button to complete search if found result to get all possible results

https://github.com/ChibaniMohamed/Polaris

**Comment by Erickesau** [comment]
I watched the video

it looks like if the entry does not take focus and text goto the console  I modified the file the first one will enable the window manager bar, the second one will give focus to the entrys when mouse Is over  try it

[https://www.mediafire.com/file/eluezh6ylz2khfu/test_4_Orion_FRS_v1.2.8_overrideredirect_false.py/file]()


[https://www.mediafire.com/file/twtlvssmi34ak78/test_5_Orion_FRS_v1.2.8_entry_with_focus.py/file]()

**Comment by Erickesau** [comment]
> can you modify the repo by adding camera recognition and make search for all faces in data set
> i mean to put new button to complete search if found result to get all possible results
> 
> https://github.com/ChibaniMohamed/Polaris

I already try Polaris look futuristic PyQt5 make exelent design but in my pc get error when search for faces that Is why I Made Orión Projet and PyQt5 look very hard to understand i Will try again maybe i make it work in my pc, 
Polaris did it work in your pc?

**Comment by akh33l** [comment]
thank you very much
the file works very well
[https://www.mediafire.com/file/eluezh6ylz2khfu/test_4_Orion_FRS_v1.2.8_overrideredirect_false.py/file]

**Comment by akh33l** [comment]
star and fork for you brother
nice work

but if can make it search for the whole database 
new button to complete search if found result to get all possible results until the end of all database

**Comment by Erickesau** [comment]
> thank you very much
> the file works very well


you're welcome so overrideredirect was the cause of the error can you please try this file it's the original without override redirect it will not hide interfaz while pick up files, maybe it was also the cause of the file dialog not showing try it and let me know if the file dialog shows so I can update the repo

[https://www.mediafire.com/file/ywaxt03sb8pj07g/test_6_Orion_FRS_v1.2.8_-_original_without_overrideredirect.py/file]()

**Comment by Erickesau** [comment]
> star and fork for you brother
> nice work
> 
> but if can make it search for the whole database 
> new button to complete search if found result to get all possible results until the end of all database

Thank you
I Will try because face recognition module it return the first match, but i will search docs maybe there Is a way to make continue searching in the full database 



I have a quiestion the sound effect Is working?

**Comment by akh33l** [comment]
> > star and fork for you brother
> > nice work
> > but if can make it search for the whole database
> > new button to complete search if found result to get all possible results until the end of all database
> 
> Thank you I Will try because face recognition module it return the first match, but i will search docs maybe there Is a way to make continue searching in the full database
> 
> I have a quiestion the sound effect Is working?

the final file also working very well
the sound effects also work very well

**Comment by Erickesau** [comment]
Thank you very much😃

**Comment by Erickesau** [comment]
Now it using hog algorithm and you can disable quickscan in the settings to make search of full database you Will get a list of result for a person or if quickscan Is enabled you Will get the first result.
Also added search for multifile and multiface you Will get a list of result for all these person if quickscan Is disabled Will search the full database and return the result with lower tolerance for each face, if quickscan Is enabled Will return the first result for each face.
